[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.48",
    "langchain-groq>=0.3.1",
    "langchain-openai>=0.3.10",
    "openai>=1.68.2",
]
